<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.App.Bundles.Tests</AssemblyName>
    <RootNamespace>FantaSim.App.Bundles.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GiantCroissant.Plate.ServiceArchi.Contracts" />
    <PackageReference Include="GiantCroissant.Plate.ServiceArchi.Core" />
    <PackageReference Include="MessagePipe" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\App.Bundles.Contracts\App.Bundles.Contracts.csproj" />
    <ProjectReference Include="..\..\plugins\App.Bundles.Core\App.Bundles.Core.csproj" />
  </ItemGroup>
</Project>
