<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.World.Plates.Topology</AssemblyName>
    <RootNamespace>FantaSim.World.Plates.Topology</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\World.Plates.Contracts\World.Plates.Contracts.csproj" />
  </ItemGroup>
</Project>
