<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Fantasim.Bundles.PlateViewer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\Fantasim.App.Bundles.Contracts\Fantasim.App.Bundles.Contracts.csproj" />
    <ProjectReference Include="..\..\contracts\Fantasim.World.Plates.Contracts\Fantasim.World.Plates.Contracts.csproj" />
  </ItemGroup>
</Project>
