<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>FantaSim.Geosphere.Plate.Runtime.Des.Tests</RootNamespace>
    <AssemblyName>Runtime.Des.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\plugins\Runtime.Des\Runtime.Des.csproj" />
    <ProjectReference Include="..\..\contracts\Runtime.Des.Contracts\Runtime.Des.Contracts.csproj" />
    <ProjectReference Include="..\..\contracts\World.Shared.Contracts\World.Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TimeDete.Time.Primitives" />
  </ItemGroup>

</Project>
