<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.App.Bundles.Contracts</AssemblyName>
    <RootNamespace>FantaSim.App.Bundles.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GiantCroissant.Crosscut.Messaging.Contracts" />
    <PackageReference Include="GiantCroissant.Plate.ServiceArchi.Contracts" />
  </ItemGroup>
</Project>
