extends VBoxContainer

var _tree: Tree
var _timer: Timer
var _previous_selection: String = ""


func _ready():
	# Create the snapshot tree
	_tree = Tree.new()
	_tree.name = "SnapshotTree"
	_tree.columns = 1
	_tree.size_flags_vertical = Control.SIZE_EXPAND_FILL
	_tree.size_flags_horizontal = Control.SIZE_EXPAND_FILL

	# Add to the placeholder container generated by boom-hud
	var container = $treeContainer
	container.add_child(_tree)

	# Auto-refresh every 2 seconds
	_timer = Timer.new()
	_timer.wait_time = 2.0
	_timer.autostart = true
	_timer.timeout.connect(_refresh_snapshot)
	add_child(_timer)

	_refresh_snapshot()
	print("[Inspector Bundle] ready")


func _refresh_snapshot():
	var bootstrap = get_node_or_null("/root/Bootstrap")
	if bootstrap == null:
		return

	var snapshot: Dictionary = bootstrap.call("CaptureSnapshotDict")
	if snapshot.is_empty():
		return

	# Preserve selection
	_previous_selection = _get_selected_bundle_id()

	_tree.clear()

	var root_item = _tree.create_item()
	root_item.set_text(0, "Bundle System")

	# Bundles section
	var bundles: Array = snapshot.get("bundles", [])
	var bundles_root = _tree.create_item(root_item)
	bundles_root.set_text(0, "Bundles (%d)" % bundles.size())

	for bundle in bundles:
		var bundle_item = _tree.create_item(bundles_root)
		bundle_item.set_text(0, bundle["id"])
		bundle_item.set_metadata(0, bundle["id"])

		_add_detail(bundle_item, "Status: %s" % bundle["status"])
		_add_detail(bundle_item, "Version: %s" % bundle["version"])
		_add_detail(bundle_item, "Display: %s" % bundle["displayName"])
		_add_detail(bundle_item, "LoadedAt: %s" % bundle["loadedAt"])
		_add_detail(bundle_item, "HasALC: %s" % str(bundle["hasALC"]))

		var tracked: Array = bundle.get("trackedNodes", [])
		if tracked.size() > 0:
			var nodes_item = _tree.create_item(bundle_item)
			nodes_item.set_text(0, "TrackedNodes (%d)" % tracked.size())
			for node_path in tracked:
				_add_detail(nodes_item, str(node_path))

		# Restore selection
		if bundle["id"] == _previous_selection:
			bundle_item.select(0)

	# Services section
	var services: Array = snapshot.get("services", [])
	var services_root = _tree.create_item(root_item)
	services_root.set_text(0, "Services (%d)" % services.size())
	for svc in services:
		_add_detail(services_root, str(svc))

	# MessageBus section
	var channels: int = snapshot.get("messageBusChannels", 0)
	var bus_root = _tree.create_item(root_item)
	bus_root.set_text(0, "MessageBus (channels: %d)" % channels)

	bootstrap.call(
		"ShowStatus",
		"Snapshot at %s" % snapshot.get("capturedAt", "?"),
	)


func _add_detail(parent_item: TreeItem, text: String):
	var item = _tree.create_item(parent_item)
	item.set_text(0, text)


func _get_selected_bundle_id() -> String:
	var selected = _tree.get_selected()
	if selected == null:
		return ""

	var current = selected
	while current != null:
		var meta = current.get_metadata(0)
		if meta is String and meta != "":
			return meta
		current = current.get_parent()

	return ""
