<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Schemas.Serialization.Tests</AssemblyName>
    <RootNamespace>Schemas.Serialization.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\schemas\FantaSim.Schemas.Serialization\FantaSim.Schemas.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>
</Project>
