#!/usr/bin/env pwsh
# Generate DTO classes from JSON Schema using QuickType.
# Usage: pwsh scripts/generate-dtos.ps1 [-Check]

param(
    [switch]$Check  # Dry-run: generate to temp and compare, fail if different
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

# Schema → output mapping
$schemas = @(
    @{
        Schema  = "project/schemas/geosphere/datasets/dataset-manifest.schema.json"
        Output  = "project/contracts/Geosphere.Plate.Datasets.Contracts/Generated/PlatesDatasetManifestDto.cs"
        TopLevel = "PlatesDatasetManifestDto"
        Namespace = "FantaSim.Geosphere.Plate.Datasets.Contracts.Generated"
    },
    @{
        Schema  = "project/schemas/geosphere/datasets/dataset-ingest-audit.schema.json"
        Output  = "project/contracts/Geosphere.Plate.Datasets.Contracts/Generated/PlatesDatasetIngestAuditDto.cs"
        TopLevel = "PlatesDatasetIngestAuditDto"
        Namespace = "FantaSim.Geosphere.Plate.Datasets.Contracts.Generated"
    }
)

$failed = $false

foreach ($s in $schemas) {
    $schemaPath = Join-Path $root $s.Schema
    $outputPath = Join-Path $root $s.Output

    if (-not (Test-Path $schemaPath)) {
        Write-Error "Schema not found: $schemaPath"
        $failed = $true
        continue
    }

    Write-Host "Generating $($s.TopLevel) from $(Split-Path -Leaf $s.Schema)..."

    # Generate with QuickType (SystemTextJson framework, C# 6 file-scoped namespaces)
    $raw = quicktype `
        --src-lang schema `
        --src $schemaPath `
        --lang csharp `
        --namespace $s.Namespace `
        --features attributes-only `
        --framework SystemTextJson `
        --csharp-version 6 `
        --array-type array `
        --top-level $s.TopLevel `
        2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Error "QuickType failed for $($s.Schema): $raw"
        $failed = $true
        continue
    }

    # Add header with nullable and CS8618 suppression (auto-generated DTOs have no constructors)
    $header = @"
// <auto-generated />
// Generated from $(Split-Path -Leaf $s.Schema)
// DO NOT EDIT - Regenerate using: task generate-dtos

#nullable enable
#pragma warning disable CS8618 // Non-nullable property uninitialized

"@

    $generated = $header + ($raw -join "`n") + "`n"

    if ($Check) {
        if (Test-Path $outputPath) {
            $existing = Get-Content $outputPath -Raw
            if ($existing -ne $generated) {
                Write-Host "MISMATCH: $($s.Output) differs from generated output" -ForegroundColor Red
                $failed = $true
            } else {
                Write-Host "  OK: $($s.Output) is up to date" -ForegroundColor Green
            }
        } else {
            Write-Host "MISSING: $($s.Output) does not exist" -ForegroundColor Red
            $failed = $true
        }
    } else {
        $dir = Split-Path -Parent $outputPath
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Set-Content -Path $outputPath -Value $generated -NoNewline
        Write-Host "  Written: $($s.Output)" -ForegroundColor Green
    }
}

if ($failed) {
    Write-Error "DTO generation failed or check found mismatches."
    exit 1
}

Write-Host "Done." -ForegroundColor Cyan
