<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.Geosphere.Plates.Topology</AssemblyName>
    <RootNamespace>FantaSim.Geosphere.Plates.Topology</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\Geosphere.Plates.Contracts\Geosphere.Plates.Contracts.csproj" />
  </ItemGroup>
</Project>
