<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.World.Plates.Tests</AssemblyName>
    <RootNamespace>FantaSim.World.Plates.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\World.Plates.Contracts\World.Plates.Contracts.csproj" />
    <ProjectReference Include="..\..\plugins\World.Plates.Topology\World.Plates.Topology.csproj" />
  </ItemGroup>
</Project>
