<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FantaSim.Geosphere.Plate.Tests</AssemblyName>
    <RootNamespace>FantaSim.Geosphere.Plate.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\Geosphere.Plate.Topology.Contracts\Geosphere.Plate.Topology.Contracts.csproj" />
    <ProjectReference Include="..\..\plugins\Geosphere.Plate.Topology.Materializer\Geosphere.Plate.Topology.Materializer.csproj" />
    <ProjectReference Include="..\..\plugins\Geosphere.Plate.Topology.Serializers\Geosphere.Plate.Topology.Serializers.csproj" />
    <ProjectReference Include="..\Geosphere.Plate.Testing.Storage\Geosphere.Plate.Testing.Storage.csproj" />
  </ItemGroup>
</Project>
