<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>FantaSim.Geosphere.Plate.Testing.Storage</RootNamespace>
    <AssemblyName>Geosphere.Plate.Testing.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\Geosphere.Plate.Topology.Contracts\Geosphere.Plate.Topology.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UnifyStorage.Abstractions" />
    <PackageReference Include="TimeDete.Time.Primitives" />
  </ItemGroup>

</Project>
